// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATyyI6lbhDckRTEgVbrlPjSjUpho1oSsA',
    appId: '1:902473744606:web:026c75d32c7a2680e9c24f',
    messagingSenderId: '902473744606',
    projectId: 'flutterchat-991ea',
    authDomain: 'flutterchat-991ea.firebaseapp.com',
    storageBucket: 'flutterchat-991ea.appspot.com',
    measurementId: 'G-QZDKY6G955',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMJz99IfILjBIbmpyyQ6cjP_t-5R3Znk',
    appId: '1:902473744606:android:5c9657dc65b50e8fe9c24f',
    messagingSenderId: '902473744606',
    projectId: 'flutterchat-991ea',
    storageBucket: 'flutterchat-991ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHKgrU_6hbTll4icgNa6uKY1KUEdkujk',
    appId: '1:902473744606:ios:299f31f998fd4f61e9c24f',
    messagingSenderId: '902473744606',
    projectId: 'flutterchat-991ea',
    storageBucket: 'flutterchat-991ea.appspot.com',
    iosClientId: '902473744606-ot0i245f7mq43eqvq6hvr3ihoq9hso5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHKgrU_6hbTll4icgNa6uKY1KUEdkujk',
    appId: '1:902473744606:ios:299f31f998fd4f61e9c24f',
    messagingSenderId: '902473744606',
    projectId: 'flutterchat-991ea',
    storageBucket: 'flutterchat-991ea.appspot.com',
    iosClientId: '902473744606-ot0i245f7mq43eqvq6hvr3ihoq9hso5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
